### ISSUE TITLE
Luma3DS 11.0 release

### ISSUE THREAD

**Issue by evan** [valx76/Luma3DS#1]
Hi, do you have a build of your timelock branch for Luma3DS 11.0 available?

Thanks and happy new year.

**Comment by evan** [comment]
I went ahead and rebased your branch on top of 11.0 here: https://github.com/evan/Luma3DS-timelock. It seems to work, but if the console is closed at the lock screen, it doesn't sleep, and when it's opened again, the Rosalina menu is frozen (or input is disabled) and the console must be power cycled. Is this a known issue?

**Comment by valx76** [comment]
Hey evan,

Happy near year to you too, thanks! :)
I will have to take a look about your issue (see if I can reproduce on Luma3DS v10.3 first, and then investigate for v11.0 if not)..
Kinda busy nowadays but will try to get back to you with an answer!

---
**EDIT**
I confirm the issue also exists on v10.3.
Thanks for reporting, I will take a look!

**Comment by evan** [comment]
Thanks! I have no idea what the correct solution is, but my initial thought was that if the timelock menu can close on entering sleep and return the console to its normal state, we could let just let the thread trigger the lock again on sleep exit.

**Comment by valx76** [comment]
That's what I was gonna go with :).
Your initial thought is correct, that's what Rosalina's menu is doing (with the `menuShouldExit` variable set [here](https://github.com/valx76/Luma3DS-Timelock/blob/master/sysmodules/rosalina/source/main.c#L137)).

**Comment by valx76** [comment]
@evan I've just fixed it, the console can now go to sleep.
It will take 10s for the console to be timelocked again when recovering from sleep mode.

**Comment by evan** [comment]
Great; I will try it out. Here is an untested build for 11.0 with the change. [boot.firm.zip](https://github.com/valx76/Luma3DS-Timelock/files/10344406/boot.firm.zip)

It's a trivial rebase on Luma3DS/master but feel free to grab my branch for 11 if you prefer.

If my kids keep flipping the lid open and shut to get 10 seconds at a time I will reopen the issue.

**Comment by evan** [comment]
Sleep appears to work properly. It would be nice if the menu resume was near-instantaneous but I'm not sure what we can do about that.

I have a couple questions now that I'm installing it:

- Does the counter reset every day at midnight?
- Does entering the code restart the count or is it disabled for the rest of the day?
- Is the counter paused during sleep?

Thanks

**Comment by valx76** [comment]
It should be near-instantaneous by changing [this line](https://github.com/LumaTeam/Luma3DS/blob/a52c3349e738647eff74867b96529ef875be27ea/sysmodules/rosalina/source/timelock.c#L101) to use `1LL` instead of `10LL`. 
The thing is I'm not sure how the sleep feature works on the DS; it might drain the battery quicker..


> **Does the counter reset every day at midnight?**
> Currently no. It's a good idea though!

> **Does entering the code restart the count or is it disabled for the rest of the day?**
> Entering the code will reset the timer so you can get the number of minutes you set in the config, back again (i.e. if you put the timer to 10min, entering the code will give you 10min more).

> **Is the counter paused during sleep?**
> Not right now. Will try to push a fix today or tomorrow.

**Comment by evan** [comment]
Nintendo Switch lets you set a limit by day of the week (using a phone app) and it will automatically reset at midnight to the next day's limit. Our Switches are set for 90 min on Saturday and Sunday only which is what I'm trying to replicate. The current system here will work, we just need to unlock it each Saturday and Sunday to get a new 90 minutes. But the Switch version is more convenient because no parent interaction is necessary. 

If you implement daily reset, I am not sure how to prevent changing the time from resetting the limit on 3DS. Maybe if the wall clock time changes by more than 90 seconds in between 60 second checks, or goes backwards, it could immediately lock for the day? This may be defeatable by power cycling after changing the time, though. 

Regarding the 10 second poll, I have no idea how sleep works either although it seems pretty power-intensive already compared to more modern devices. Ideally we could register an interrupt to fire on wake instead.

**Comment by evan** [comment]
I tested the impact of sleep on the counter and it does seem to pause and resume correctly.

It would be nice/easier to validate if the timelock Rosalina menu displayed the elapsed and target time.

**Comment by valx76** [comment]
I've pushed a new update that makes sure the timer stops when in sleep mode.
I like the idea of having kind of a planning (limit defined per day, daily reset) but unfortunately I will not have the time to work on it anytime soon..

**Comment by evan** [comment]
Thanks for the fix.

I'll try to add some features and see if I can make any progress.

**Comment by evan** [comment]
I've been leaving the console in locked sleep mode for 2 days, with a 2 second poll timer, and haven't seen any battery loss. 

From this, the fact that it seems to always take the full number of seconds to show the lock menu on wake, and the fact that in my previous test, it did not seem to advance the counter during sleep, I wonder if `svcSleepThread` never resumes until the console is awakened.
